Koniverse/SubWallet-Mobile

- src/screens/Home/Crypto/ActionButtonContainer.tsx
> Fix some UI bug for Buy feature

- src/predefined/dAppSites.ts
> Add some dApps to browser's predefined list

- src/screens/Home/Staking/Network/StakingNetworkItem.tsx
> Update some information at the Select network to stake screen

- src/screens/AttachAccount/AttachQrSignerConfirm.tsx
> Fix bug showing not enough account on the account list of the dApp

- src/App.tsx
- src/screens/Staking/Compound/CompoundActionScreen.tsx
- src/screens/Staking/Stake/StakeActionScreen.tsx
- src/screens/Staking/UnStake/UnStakeActionScreen.tsx
- src/screens/TransferNft/TransferNftScreen.tsx
> Fix bug back the previous screen when user swipes screen (iOS) or touch the back button (Android)

- src/screens/Home/Crypto/ActionButtonContainer.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> Fix bug crash app when send fund using an EVM account that is not connected to any network

- src/screens/AttachAccount/AttachQrSignerConfirm.tsx
> Update logic for Attach QR signer account

- src/screens/Home/Browser/BrowserTab.tsx
- src/utils/browser.ts
> Fix bug crash app in case click on the Get Subsquare button when connecting dApp

- src/screens/Home/Crypto/layers/TokenGroup.tsx
> Display incorrect order of default network

- src/screens/Home/Crypto/layers/TokenGroup.tsx
> FIx bug not show network when an account has subtoken but no maintoken

- ios/Podfile.lock
- src/predefined/dAppSites.ts
> Add subsquare.io and moons.money to predefined list

- src/components/design-system-ui/button/index.tsx
- src/components/design-system-ui/index.ts
- src/components/design-system-ui/logo/index.tsx
- src/components/design-system-ui/logo/style/index.ts
- src/components/design-system-ui/page-icon/index.tsx
- src/components/design-system-ui/squircle/index.tsx
> Update UI for button, logo, squircle

- src/components/pageWrapper.tsx
> [issue-343] Add Page Wrapper HOC

- src/components/design-system-ui/index.ts
- src/components/design-system-ui/modal/DeleteModal.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/components/design-system-ui/modal/index.tsx
- src/components/design-system-ui/modal/style/index.ts
> [issue-355] Add delete modal

- src/screens/RestoreJson.tsx
> Update RestoreJson screen

- src/screens/ImportPrivateKey.tsx
> Update Import Private Key screen

- src/components/Field/Balance.tsx
- src/components/common/ActionModal/index.tsx
- src/components/design-system-ui/tag/index.tsx
- src/hooks/screen/Home/Staking/useFetchStaking.ts
- src/hooks/types.ts
- src/screens/Home/Staking/Balance/StakingBalanceItem.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetail.tsx
- src/screens/Home/Staking/StakingScreen.tsx
- src/screens/NetworksSetting.tsx
> Update Staking, Staking Detail screen

- src/components/Modal/SelectNetworkModal.tsx
- src/hooks/screen/Home/useGetChainSlugs.ts
- src/hooks/screen/ImportNft/useGetContractSupportedChains.ts
- src/screens/Home/index.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-378] Update import NFT

- src/components/ActionButton.tsx
- src/components/Modal/common/AccountSelector.tsx
- src/components/Modal/common/TokenSelector.tsx
- src/components/TokenSelectItem.tsx
- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/hooks/screen/useFetchChainInfo.ts
- src/screens/Home/Crypto/ReceiveModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/utils/index.tsx
> [Issue-385] Update Receive QR modal

- src/screens/ImportToken/ImportToken.tsx
> [Issue-387]: Update UI for ImportToken

- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Crypto/index.tsx
> [issue-385b] Fix Receive QR Modal auto close after web runner fetch data

- src/components/FlatListScreen.tsx
- src/components/NetworkAndTokenToggleItem.tsx
- src/components/common/TokenBalanceItem/index.tsx
- src/components/common/TokenGroupBalanceItem/index.tsx
- src/components/design-system-ui/typography/style/index.ts
- src/screens/Home/Crypto/CustomizationModal.tsx
- src/screens/Home/Crypto/TokenDetailModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-391] Update Customization Modal

- src/components/Modal/common/TokenSelector.tsx
- src/components/NetworkAndTokenToggleItem.tsx
- src/components/design-system-ui/logo/LogoMap.ts
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/hooks/screen/Home/Crypto/utils.ts
- src/screens/AccountsScreen.tsx
- src/screens/Home/Crypto/ServiceModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/MasterPassword/ApplyMasterPassword/ApplyDone.tsx
- src/screens/MasterPassword/ApplyMasterPassword/index.tsx
- src/stores/types.ts
> [Issue-395]: Update UI for Buy Token screen

- src/AppNavigator.tsx
- src/components/Field/NetworkName.tsx
- src/components/Field/RpcSelect.tsx
- src/components/Field/Text.tsx
- src/components/Input/InputText.tsx
- src/components/NetworkAndTokenToggleItem.tsx
- src/components/common/RpcSelectorModal/index.tsx
- src/components/design-system-ui/select-item/index.tsx
- src/hooks/screen/Home/Staking/useGetStakingNetworks.ts
- src/hooks/screen/useFetchChainState.ts
- src/routes/index.ts
- src/screens/Home/Staking/Balance/StakingBalanceItem.tsx
- src/screens/NetworkSettingDetail.tsx
- src/screens/NetworksSetting.tsx
- src/utils/index.tsx
> [Issue-397]: Update UI for Network Config Detail screen

- src/components/MetaInfo/context.ts
- src/components/MetaInfo/hooks/useGeneralStyles.ts
- src/components/MetaInfo/index.tsx
- src/components/MetaInfo/parts/AccountGroupItem.tsx
- src/components/MetaInfo/parts/AccountItem.tsx
- src/components/MetaInfo/parts/ChainItem.tsx
- src/components/MetaInfo/parts/DataItem.tsx
- src/components/MetaInfo/parts/DefaultItem.tsx
- src/components/MetaInfo/parts/DisplayTypeItem.tsx
- src/components/MetaInfo/parts/NumberItem.tsx
- src/components/MetaInfo/parts/StatusItem.tsx
- src/components/MetaInfo/parts/TotalItem.tsx
- src/components/MetaInfo/parts/TransferItem.tsx
- src/components/MetaInfo/parts/index.tsx
- src/components/MetaInfo/shared.tsx
- src/components/MetaInfo/style/index.ts
- src/components/MetaInfo/types.ts
- src/components/SubWalletAvatar.tsx
- src/components/common/AvatarGroup/index.tsx
- src/components/design-system-ui/typography/style/index.ts
- src/providers/TransactionContext.tsx
- src/styles/sharedStyles.ts
- src/types/index.ts
- src/types/transaction.ts
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-399] Update MetaInfo component

- src/components/Input/InputAddress.tsx
- src/screens/Confirmations/Transaction/index.tsx
- src/screens/Confirmations/Transaction/variants/SendNft.tsx
- src/screens/Confirmations/Transaction/variants/index.tsx
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/Home/NFT/NFTStackScreen.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/helper/index.ts
- src/screens/Transaction/helper/nftParamsHandler.ts
- src/utils/index.tsx
> [Issue-412] Update send NFT

- ios/Podfile
- ios/Podfile.lock
- package.json
- src/components/common/ErrorFallbackScreen/style/index.tsx
- src/screens/AttachAccount/ImportAccountQrConfirm.tsx
- src/screens/ExportAccount.tsx
- yarn.lock
> [issue-433] Update Import by QR

- package.json
- src/App.tsx
- src/AppNavigator.tsx
- src/components/Field/AccountSelect.tsx
- src/components/Field/TokenSelect.tsx
- src/components/Input/InputAddress.tsx
- src/components/Input/InputAmount/index.tsx
- src/components/Modal/common/ChainSelector.tsx
- src/components/NetworkSelectItem.tsx
- src/components/design-system-ui/button/PropsType.tsx
- src/components/design-system-ui/button/index.tsx
- src/hooks/balance/useGetBalance.ts
- src/hooks/screen/Transaction/useTransaction.ts
- src/providers/DataContext.tsx
- src/routes/index.ts
- src/screens/Confirmations/Transaction/index.tsx
- src/screens/Confirmations/Transaction/variants/TransferBlock.tsx
- src/screens/Confirmations/Transaction/variants/index.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/parts/FreeBalance.tsx
- src/stores/feature/common/AssetRegistry.ts
- src/stores/index.ts
- src/stores/types.ts
- src/stores/utils/index.ts
> [Issue-436] Update send fund screen

- ios/Podfile.lock
- src/screens/Home/index.tsx
- yarn.lock
> [issue-452] Add progress bar when open app

- src/components/ActionButton.tsx
- src/components/BalancesVisibility.tsx
- src/components/ScreenContainer.tsx
- src/components/common/TokenGroupBalanceItem/index.tsx
- src/screens/Home/Crypto/CustomizationModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/Home/Crypto/TokenSearchModal.tsx
- src/screens/Home/Crypto/layers/shared.tsx
- src/screens/Home/Crypto/shared/TokensLayout.tsx
> [Issue-445] Update crypto screen

- src/components/FlatListScreen.tsx
- src/components/Search.tsx
- src/components/common/HistoryItem/index.tsx
- src/components/common/HistoryItem/style/index.ts
- src/screens/Home/History/index.tsx
- src/screens/Home/NFT/Collection/NftCollectionItem.tsx
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/Home/NFT/Item/NftItem.tsx
- src/screens/Transaction/NFT/index.tsx
> [Issue-446, 447] Update History and NFT

- src/AppNavigator.tsx
- src/components/Input/InputText.tsx
- src/components/NetworkAndTokenToggleItem.tsx
- src/components/Search.tsx
- src/components/design-system-ui/modal/DeleteModal.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/components/design-system-ui/modal/style/index.ts
- src/hooks/screen/useTokenGroup.ts
- src/routes/index.ts
- src/screens/ImportNetwork.tsx
- src/screens/NetworkSettingDetail.tsx
- src/screens/NetworksSetting.tsx
- src/utils/chainAndAsset.ts
> Update UI for Setting/Network

- src/components/design-system-ui/number/index.tsx
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/index.tsx
- src/types/index.ts
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [issue-448] update UI crowdloan

- src/components/LazySectionList.tsx
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
> [issue-448b] fix warning Crowdloan

- src/AppNavigator.tsx
- src/components/Header.tsx
- src/components/Modal/Base/SubWalletModal.tsx
- src/components/design-system-ui/qr-code/style/index.ts
- src/routes/index.ts
- src/screens/Home/Crypto/ReceiveModal.tsx
- src/screens/Home/History/Detail/index.tsx
- src/screens/Home/History/index.tsx
- src/screens/Settings/index.tsx
- src/styles/color.ts
- Update Receive Modal
- Add History screen to Settings screen
> Update Receive Modal, Add History screen to Settings screen

- src/utils/number.ts
> [issue-474] Number Abbreviation

- src/components/common/AccountActionButton/index.tsx
- src/components/common/UnlockModal/index.tsx
- src/hooks/useCheckLogin.ts
- src/screens/Home/FirstScreen.tsx
> Fix bug require MasterPassword in First Screen

- src/components/Confirmation/ConfirmationGeneralInfo/index.tsx
- src/components/Confirmation/ConfirmationGeneralInfo/styles/index.ts
- src/components/Confirmation/index.ts
- src/routes/index.ts
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/styles/index.ts
- src/screens/CreateAccount/index.tsx
> [Issue-417] [Confirmation] [Auth] Fix create new account func

- src/components/TokenSelectItem.tsx
- src/components/common/Modal/UnlockModal/index.tsx
- src/predefined/transak.ts
- src/screens/AccountsScreen.tsx
- src/screens/Home/Crypto/ServiceModal.tsx
- src/screens/Home/FirstScreen.tsx
- src/screens/MasterPassword/ApplyMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/Settings/index.tsx
> Show incorrect network when Buy token Astr

- src/hooks/screen/useGoHome.ts
- src/routes/home.ts
- src/screens/Home/index.tsx
> [issue-523] Fix bugs Home screen

- src/components/FlatListScreen.tsx
- src/components/LazySectionList.tsx
- src/screens/Home/History/index.tsx
Fix some issues related to History
> [Issue-507, 508] Fix some issues related to History

- src/components/ToggleItem.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Settings/General/index.tsx
- src/screens/Settings/Security/index.tsx
- src/screens/Settings/index.tsx
> Update UI for Settings screen and fix bug in History screen

- src/components/PinCodeField.tsx
- src/screens/Settings/Security/PinCodeScreen.tsx
- src/stores/index.ts
> Fix bug do not save PIN code setting

- src/components/ActivityLoading.tsx
- src/components/ImagePreview.tsx
- src/components/LazyFlatList.tsx
- src/components/LazySectionList.tsx
- src/components/design-system-ui/button/index.tsx
- src/screens/Home/History/index.tsx
- src/screens/LoadingScreen.tsx
- src/screens/Transaction/parts/FreeBalance.tsx
> FIx UI bugs related to History feature

- src/components/BalancesVisibility.tsx
- src/components/design-system-ui/button/index.tsx
- src/components/design-system-ui/tag/style/index.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/TransferNft/NftTransferConfirm.tsx
- src/screens/TransferNft/NftTransferResult.tsx
> Update UI for Crypto Screen, NFT Screen

- src/hooks/common/useFetchChainInfo.ts
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/messaging/index.ts
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- #519: Fix some issues related NFT feature
- #526: Only show one toast at a time
> [Issue-519, 526] Fix some issues related NFT feature, Only show one toast at a time

- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- #513
- Fix stand on token detail when change account
- Fix stand on token detail when change account
- No
- No
> [Issue-513] UI bug when switch account in case standing on the Token Detail screen

- src/components/AccountSettingButton.tsx
- src/components/design-system-ui/tag/style/index.tsx
- src/hooks/screen/Home/Crowdloans/useGetCrowdloanList.ts
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
- #497
- Update UI
- Update UI
- No
- No
> [Issue-497] Crowdloan data is displayed incorrectly

- src/screens/Home/History/index.tsx
- src/stores/index.ts
- [Issue-566] Persist Setting after closing app
- [Issue-509] Update history search logic
> [Issue- 509, 566] Persist Setting after closing app, update history search logic

- src/components/Field/Network.tsx
- src/components/Input/InputAddress.tsx
- src/components/Input/InputAmount/index.tsx
- src/components/Input/InputAmount/style/index.ts
- src/screens/Account/AttachReadOnly/index.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/styles/sharedStyles.ts
- [Issue-567] Add placeholder for fields
- [Send fund] Disable fields in some case
> [Issue-567] Add placeholder for fields, [Send fund] Disable fields in some case

- src/components/common/RpcSelectorModal/index.tsx
- src/screens/NetworkSettingDetail.tsx
- #520
- [UpdateChain] Fix bug cannot save
- [UpdateChain] Fix bug cannot save
- No
- No
> [Issue-520] UI bugs when configuring network

- src/screens/Account/RestoreJson/index.tsx
- src/screens/MasterPassword/ApplyMasterPassword/index.tsx
> Handling the case of importing multiple accounts using a JSON file

- src/components/Input/InputAddress.tsx
- src/components/Textarea.tsx
- src/screens/Account/AttachReadOnly/index.tsx
- src/screens/Account/CreateAccount/VerifySecretPhrase.tsx
- src/screens/Account/ImportPrivateKey/index.tsx
- src/screens/Account/ImportQrCode/index.tsx
- src/screens/Account/ImportSecretPhrase/index.tsx
- src/screens/Account/RestoreJson/index.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/MasterPassword/ApplyMasterPassword/index.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
> Fix bug do not submit data when the user uses the Enter key on the virtual keyboard

- package.json
- src/AppNavigator.tsx
- yarn.lock
> [issue-545] set color for bottom safe area on Android

- src/components/Field/PoolSelector/index.tsx
- src/components/Field/ValidatorSelector/index.tsx
- src/components/Modal/common/PoolSelector.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Transaction/Stake/index.tsx
> [issue-585] Fix bugs when perform staking actions

- src/components/Modal/common/ValidatorSelector.tsx
- src/components/Modal/common/ValidatorSelectorDetailModal.tsx
- src/screens/Confirmations/parts/Sign/Substrate.tsx
- src/screens/Transaction/Stake/index.tsx
- src/utils/transaction/stake.ts
> [Issue-583]: Fix bug undefined is not an object when staking

- src/screens/Transaction/index.tsx
> [Issue-572]: Fix bug navigate incorrect screen in case click on Back to homepage when send NFT

- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/hooks/screen/Home/Crypto/utils.ts
> [Issue-595]: Fix bug show incorrect list account when user receive address

- src/components/Modal/SelectAccountTypeModal.tsx
> [Issue-606] Disable button Confirm if no account type is selected when creating new account

- src/screens/ImportToken/ImportToken.tsx
> [Issue-494]: Fix bug for ImportToken

- src/components/Modal/common/AccountSelector.tsx
- src/components/Modal/common/ChainSelector.tsx
- src/components/Modal/common/TokenSelector.tsx
- src/components/TokenSelectItem.tsx
> [Issue-635]: Upgrade UI for Token selector item, Account selector item

- src/screens/Account/AccountsScreen/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
> [Issue-616]: Add search box for select account modal

- src/hooks/account/usePreCheckReadOnly.ts
- src/screens/Home/Staking/StakingDetail/StakingActionModal.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
> [Issue-619]: Fix UI bugs related to Staking feature

- src/screens/Confirmations/index.tsx
- src/screens/Confirmations/parts/Qr/DisplayPayload/DisplayPayloadModal.tsx
- src/screens/Confirmations/parts/Qr/DisplayPayload/styles/index.ts
> [Issue-627]: Missed the Scan QR screen when approving transactions of QR-signer account

- src/screens/Account/ImportPrivateKey/index.tsx
- src/screens/Account/ImportSecretPhrase/index.tsx
> [Issue-641, 643] Allow whitespace when inputting private key or seed phrase, fix bug still enable "Derive from another account" 

- src/assets/index.ts
- src/assets/menu-bar.svg
- src/components/Header.tsx
- src/components/SubHeader.tsx
- src/screens/Home/Crypto/ReceiveModal.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Settings/index.tsx
> [Issue-644]: Update UI the Setting screen follow by design

- src/AppNew.tsx
- src/components/common/Account/AccountCreationArea/index.tsx
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/Stake/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
> [Issue-651]: Fix bug still submit successfully in case do not select account when unstake

- src/components/Modal/common/AccountSelector.tsx
- src/components/Modal/common/ChainSelector.tsx
- src/components/Modal/common/TokenSelector.tsx
- src/components/common/RpcSelectorModal/index.tsx
- src/hooks/screen/useAccountBalance.ts
- src/screens/NetworkSettingDetail.tsx
- src/screens/NetworksSetting.tsx
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
> [Issue-613] Fix crashing issue after deleting custom token or chain

- src/components/Textarea.tsx
- src/screens/Account/ImportPrivateKey/index.tsx
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
> [Issue-663]: Fix bug ImportPrivateKey in Android

- src/screens/Account/ImportPrivateKey/index.tsx
> [Issue-663]: Fix bug ImportPrivateKey

- src/screens/Home/Crypto/CustomizationModal.tsx
> [Issue-654]: Fix bug UI for CustomizationModal

- src/components/common/TokenBalanceItem/index.tsx
- src/components/common/TokenBalanceItem/style/index.ts
- src/components/common/TokenGroupBalanceItem/index.tsx
- src/components/design-system-ui/tag/style/index.tsx
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/Staking/Balance/StakingBalanceItem.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/StakingScreen.tsx
> [Issue-698] Update UI for token, crowdload, staking item

- src/screens/Home/FirstScreen.tsx
> [issue-703] add term and condition referrence into firstscreen

- src/components/EmptyList.tsx
- src/components/common/Modal/DeriveAccountModal/index.tsx
- src/components/common/TokenBalanceItem/index.tsx
- src/components/common/TokenBalanceItem/style/index.ts
- src/components/common/TokenGroupBalanceItem/index.tsx
- src/components/common/TokenGroupBalanceItem/style/index.ts
- PR for #685 
- PR for #686  
- [698]: Update token item style
> [Issue-698][Issue-685][Issue-686]

- src/components/Input/InputAmount/index.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/Transaction/SendFund/index.tsx
- PR for #700 
- PR for #707 
- PR for #711
> [Issue-700][Issue-707][Issue-711] Fix issue related to import token, update send fund validation logic

- src/screens/Transaction/Unbond/index.tsx
> [Issue-702] Hide collators do not meet condition to unstake

- src/components/ContainerWithSubHeader.tsx
- src/components/FlatListScreen.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
> [Issue-669]: Fix bug can't watch information in the end of list in case sroll

- src/components/Input/InputAddress.tsx
- src/components/Modal/common/TokenTypeSelector.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/types/asset.ts
> [Issue-709] Fix some UI issues on the import token, import NFT screens

- src/screens/Transaction/SendFund/index.tsx
> [Issue-724] Fix issue related to max transfer when changing destination chain

- src/components/Modal/common/TokenSelector.tsx
> [Issue-655]: Fix bug do not search by token symbol and network name

- src/screens/Home/Crypto/shared/TokensLayout.tsx
> [Issue-727] Update UI for Token screen in case token group list is empty

- src/components/ContainerWithSubHeader.tsx
> [Issue-669]: Fix bug UI for Header

- src/components/MetaInfo/parts/ChainItem.tsx
- src/components/MetaInfo/parts/DataItem.tsx
- src/components/MetaInfo/parts/DefaultItem.tsx
- src/components/MetaInfo/parts/NumberItem.tsx
- src/components/MetaInfo/parts/StatusItem.tsx
- src/components/MetaInfo/types.ts
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
> [Issue-715]: Fix bug can't open the Staking detail screen

- src/hooks/screen/useScanExplorerAddressUrl.ts
- src/screens/AddProvider.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
- src/screens/ImportNetwork.tsx
- src/screens/NetworkSettingDetail.tsx
- src/screens/Tokens/index.tsx
- PR for #730
- PR for #748
- PR for #750
- PR for #726 
- PR for #744
> [Issue-730][Issue-748][Issue-750][Issue-726][Issue-744]

- src/AppNew.tsx
- src/components/common/Modal/ConfirmModal/index.tsx
- src/components/common/Modal/ConfirmModal/styles/index.ts
- src/hooks/chain/useChainChecker.ts
- src/providers/AppModalContext.tsx
- src/screens/Transaction/SendFund/index.tsx
> [issue-757] Show turn on chain popup in Transfer screen

- src/screens/Transaction/Unbond/index.tsx
- yarn.lock
> [issue-746] Show 'Max' button when unstake

- src/components/Header.tsx
- src/components/ToggleItem.tsx
- src/components/common/Account/Item/AccountItemBase/styles/index.ts
- src/routes/index.ts
- src/screens/Transaction/SendFund/index.tsx
> [Issue-628]: Fix bug can not approve transaction via QR code

- src/screens/Confirmations/variants/Transaction/variants/SendNft.tsx
- src/screens/Confirmations/variants/Transaction/variants/TransferBlock.tsx
> [Issue-742]: Fix bug UI Confirmation screen on Android

- src/constants/transaction.ts
- src/hooks/screen/Transaction/useTransaction.ts
- src/hooks/screen/useFormControl.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/types/transaction.ts
> [issue-757] fix callstack error

- src/components/common/StakingTab/index.tsx
- src/screens/Transaction/Stake/index.tsx
> [Issue-771]: Fix bug can't select token in case change Nominate to Pool when specific account mode

- src/components/Header.tsx
- src/components/Scanner/AddressScanner.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-628]: Fix bug enable chain and scan for SendFund

- src/hooks/screen/Transaction/useTransaction.ts
- src/stores/index.ts
> [issue-773] Use MMKV storage to inhance redux persist performance

- src/AppNavigator.tsx
- src/components/Header.tsx
- src/components/SubScreenContainer.tsx
- src/routes/index.ts
- src/routes/transaction/transactionAction.ts
- src/routes/wrapper.ts
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/StakingDetail/StakingActionModal.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
- src/screens/Home/index.tsx
- src/screens/Settings/Security/index.tsx
- src/screens/Settings/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/TransactionScreen.tsx
> [issue-697]: Fix bug for slide right Setting screen

- src/components/Header.tsx
- src/components/Modal/Base/SubWalletFullSizeModal.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [issue-628]: Fix route for Right header button and some UI bug

- src/components/Header.tsx
- src/components/Scanner/AddressScanner.tsx
- src/components/Scanner/QrAddressScanner.tsx
- src/routes/index.ts
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/WebViewDebugger.tsx
> [issue-788, 789]: Fix some UI bug for TokenGroupsDetail screen

- src/AppNavigator.tsx
- src/components/Input/InputAddressV2.tsx
- src/screens/Home/index.tsx
- src/screens/Transaction/SendFund/index.tsx
> [Issue-788]: Fix bug crash app when scan to SendFund

- src/components/Modal/AddressBook/EditContactModal.tsx
- src/components/Modal/AddressBook/ReadonlyAddressField.tsx
- src/screens/ImportToken/ImportNft.tsx
> [Issue-794]: Fix bug in ImportNFT screen and toast for EditContactModal

- src/components/AccountSettingButton.tsx
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Home/Crypto/ReceiveModal.tsx
- src/screens/Transaction/helper/staking/stakingHandler.ts
> [Issue-796]: Error page in case touch Icon account in Browser tab and fix some UI bugs

- src/hooks/screen/Transaction/useTransaction.ts
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/NetworksSetting.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-785]: Add message turn on chain in import Token and import NFT screen

- src/components/Modal/common/ValidatorSelector.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/NetworksSetting.tsx
- src/screens/Tokens/index.tsx
> [Issue-792]: Show duplicate network, token in case apply multi conditions when filter

- src/screens/NetworksSetting.tsx
> [Issue-811]: Fix bugs related to the Manage network feature in Build 185

- .github/workflows/push-koni-dev-build.yml
- scripts/autocheck.mjs
- scripts/build-android.mjs
- scripts/build-ios.mjs
- scripts/common.mjs
Optimize build information in discord
> [Issue-677] Update build message

- src/screens/Transaction/SendFund/index.tsx
> [issue-621] Consider handling in case validate amount

- src/screens/Account/AttachReadOnly/index.tsx
- src/screens/Confirmations/index.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Confirmations/variants/NotSupportConfirmation/index.tsx
- src/screens/Confirmations/variants/NotSupportConfirmation/styles/index.ts
- src/screens/Settings/Security/DAppAccess/DAppAccessDetailScreen.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-842]: Allow DApp access to watch-only account

- src/components/ContainerWithSubHeader.tsx
- src/components/FlatListScreen.tsx
- src/components/Modal/PasswordModal.tsx
- src/components/Modal/SelectAccountTypeModal.tsx
- src/components/SubHeader.tsx
- src/components/common/Modal/DeleteModal/index.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/parts/TransactionHeader/index.tsx
> [Issue-853]: Update UI - Header on list view

- src/components/design-system-ui/select-item/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/style/index.ts
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-810]: Update UI - Change master password

- src/components/Modal/PasswordModal.tsx
- src/screens/Account/AccountExport/index.tsx
> [Issue-807]: Allow user exported and download the JSON file

- src/AppNavigator.tsx
- src/components/Field/ServiceSelect.tsx
- src/components/Field/TokenSelect.tsx
- src/components/Modal/AccountActionSelectModal.tsx
- src/components/Modal/common/AccountSelectorNew.tsx
- src/components/Modal/common/TokenSelectorNew.tsx
- src/components/common/SelectModal/BasicSelectModal.tsx
- src/components/common/SelectModal/index.tsx
- src/components/common/SelectModal/parts/SelectModalField.tsx
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/routes/wrapper.ts
- src/screens/Home/Crypto/BuyToken.tsx
- src/screens/Home/Crypto/ServiceModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/types/modalRef.ts
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-764]: Update UI - Buy Token

- src/components/SubHeader.tsx
- src/components/common/Confirmation/ConfirmationGeneralInfo/index.tsx
- src/components/common/Confirmation/ConfirmationGeneralInfo/styles/index.ts
- src/screens/Confirmations/index.tsx
- src/screens/Confirmations/parts/Detail/Base.tsx
- src/screens/Confirmations/parts/Detail/Evm/Transaction.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/styles/index.ts
- src/screens/Confirmations/variants/MetadataConfirmation/index.tsx
- src/screens/Confirmations/variants/MetadataConfirmation/styles/index.ts
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-823]: Upgrade UI Browser - DApp Confirmation

- src/components/ServiceSelectItem.tsx
- src/components/SubHeader.tsx
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/predefined/transak.ts
- src/routes/wrapper.ts
- src/screens/Home/Crypto/BuyToken.tsx
- src/screens/Home/Crypto/ServiceModal.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/Settings/Security/index.tsx
> [Issue-764]: Recover lost code

- src/screens/Account/AttachReadOnly/index.tsx
> [Issue-833]: Error page in adding watch-only account screen

- src/messaging/index.ts
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
> [Issue-871]: Implement reload nft and reload staking

- src/components/Modal/common/PoolSelector.tsx
- src/components/Modal/common/ValidatorSelector.tsx
> [Issue-875]: Update UI - Add the sort for the Select Pool/Validator/Collator/dApp screen

- src/screens/Account/AccountsScreen/index.tsx
> [Issue-879]: Fix bug still show Token detail screen when switch account

- src/AppNavigator.tsx
- src/components/Modal/Base/ModalBase.tsx
- src/components/common/ForgotPasswordModal/index.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/hooks/useAppLock.ts
- src/messaging/index.ts
- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/LockScreen.tsx
- src/screens/Settings/index.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
> [Issue-812]: Reset wallet feature

- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/Settings/Security/DAppAccess/DAppAccessDetailScreen.tsx
> [Issue-884, 882]: Autofocus password when create master password & Allow search by address on Manage website access detail screen

- ios/Podfile.lock
- src/components/Modal/ConnectWebsiteModal.tsx
- src/components/common/ConfirmationHeader/index.tsx
- src/predefined/dAppSites.ts
- src/screens/Home/Browser/BrowserHome.tsx
- src/screens/Home/Browser/BrowserListByCategory.tsx
- src/screens/Home/Browser/BrowserScripts.ts
- src/screens/Home/Browser/BrowserSearch.tsx
- src/screens/Home/Browser/BrowserTab.tsx
- src/screens/Home/Browser/Shared/IconItem.tsx
- src/screens/Home/Browser/styles/BrowserTab.ts
- src/utils/browser.ts
> [issue-873] Fix browser issue

- src/AppNew.tsx
- src/components/Modal/AddressBook/AddContactModal.tsx
- src/components/Modal/AddressBook/EditContactModal.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/components/design-system-ui/toast/index.tsx
- src/hooks/account/usePreCheckReadOnly.ts
- src/hooks/chain/useChainChecker.ts
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/hooks/screen/Transaction/useSelectValidators.ts
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Account/ConnectQrSigner/index.tsx
- src/screens/Account/ImportQrCode/index.tsx
- src/screens/AddProvider.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/Home/Staking/StakingDetail/StakingActionModal.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
- src/screens/ImportNetwork.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/NetworkSettingDetail.tsx
- src/screens/Settings/NetworkConfigDetail.tsx
- src/screens/Tokens/ConfigureToken.tsx
- src/screens/Transaction/SendFund/index.tsx
> [Issue-808]: Update UI -Toast

- src/AppNavigator.tsx
- src/components/ContainerWithSubHeader.tsx
- src/components/Header.tsx
- src/components/common/Account/AccountSelectField/index.tsx
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/Stake/index.tsx
- src/screens/Transaction/TransactionScreen.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
- src/screens/Transaction/parts/TransactionHeader/index.tsx
- src/screens/Transaction/parts/TransactionLayout/index.tsx
> [Issue-880]: Fix bugs when click on actions on header when standing transaction screen

- android/app/src/main/AndroidManifest.xml
- ios/SubWalletMobile.xcodeproj/project.pbxproj
- ios/SubWalletMobile/AppDelegate.mm
- ios/SubWalletMobile/SubWalletMobile.entitlements
- package.json
- src/AppNavigator.tsx
- src/hooks/screen/Home/Crowdloans/useGetCrowdloanList.ts
- src/routes/home.ts
- src/routes/index.ts
- src/screens/Home/Browser/BrowserTabsManager.tsx
- src/screens/Home/Browser/index.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/index.tsx
- src/types/index.ts
- src/utils/browser.ts
- yarn.lock
> [issue-779] Config universal deeplink

- src/components/Modal/SelectAccountTypeModal.tsx
- src/components/Modal/common/PoolSelector.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/components/common/RpcSelectorModal/index.tsx
- src/components/common/SelectModal/BasicSelectModal.tsx
- src/components/common/SelectModal/index.tsx
- src/screens/NetworkSettingDetail.tsx
> [Issue-777]: Update New SelectModal for PoolSelector and ValidatorSelector

- src/components/Browser/styles/BrowserItem.ts
- src/components/FlatListScreen.tsx
- src/components/LazyFlatList.tsx
- src/components/LazySectionList.tsx
- src/components/common/SelectModal/index.tsx
- src/constants/itemHeight.ts
- src/screens/Home/Browser/BrowserHome.tsx
- src/screens/Home/Browser/BrowserListByCategory.tsx
- src/screens/Home/Browser/BrowserSearch.tsx
- src/screens/Home/Browser/Shared/IconItem.tsx
- src/screens/Home/Browser/Shared/styles/IconItem.ts
- src/screens/Home/Browser/styles/BrowserHome.ts
- src/screens/Home/Browser/styles/BrowserListByCategory.ts
- src/screens/Home/Crypto/CustomizationModal.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/layers/shared.tsx
- src/screens/Home/Crypto/shared/TokensLayout.tsx
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
> [issue-874] Improve list performance round 2nd

- src/AppNavigator.tsx
- src/components/Field/AccountSelect.tsx
- src/components/Field/TokenSelect.tsx
- src/components/Input/InputAddressV2.tsx
- src/constants/ledger.ts
- src/constants/transaction.ts
- src/hooks/account/usePreCheckAction.ts
- src/hooks/screen/Transaction/useTransactionV2.ts
- src/screens/Transaction/SendFundV2/Amount.tsx
- src/screens/Transaction/SendFundV2/AmountValueConverter.tsx
- src/screens/Transaction/SendFundV2/index.tsx
- src/screens/Transaction/SendFundV2/styles/Amount.ts
- src/screens/Transaction/SendFundV2/styles/index.ts
- src/screens/Transaction/TransactionScreen.tsx
- src/screens/Transaction/parts/FreeBalance.tsx
- src/screens/Transaction/parts/FreeBalanceDisplay.tsx
- src/types/index.ts
> [Issue-815] Update new UI for send fund screen

- src/screens/Home/NFT/Collection/NftCollectionItem.tsx
- src/screens/Home/NFT/Item/NftItem.tsx
> [issue-915] UI bugs on the NFT list screen (Android device)

- src/components/ImagePreview.tsx
> [Issue-142]: Bug can not display NFT Video on Android

- src/components/ContainerWithSubHeader.tsx
- src/components/FlatListScreen.tsx
- src/components/Header.tsx
- src/components/Modal/AddressBook/AddContactModal.tsx
- src/components/Modal/AddressBook/style/EditContactModal.ts
- src/components/Modal/common/PoolSelector.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/components/Modal/style/ConnectWebsiteModal.ts
- src/components/Scanner/QrAddressScanner.tsx
- src/components/Scanner/SignatureScanner.tsx
- src/components/design-system-ui/modal/SwFullSizeModal.tsx
- src/hooks/modal/useUnlockModal.ts
- src/hooks/useFilterModal.ts
- src/screens/Confirmations/parts/Qr/DisplayPayload/DisplayPayloadModal.tsx
- src/screens/Confirmations/parts/Qr/DisplayPayload/styles/index.ts
- src/screens/Confirmations/parts/Sign/Evm.tsx
- src/screens/Confirmations/parts/Sign/Substrate.tsx
- src/screens/Settings/AddressBook/index.tsx
> [Issue-815]: Update UI for Polkadot Vault transaction

- src/screens/Transaction/SendFundV2/index.tsx
> [Issue-939]: Bug related to Send fund

- src/hooks/balance/useGetBalance.ts
> [issue-942] Re-check re-connect network on transaction screen

- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
> [issue-920] Support sort token by value

- src/AppNavigator.tsx
- src/AppNew.tsx
- src/components/Field/Password.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/components/ScreenContainer.tsx
- src/components/WalletConnect/ConnectionItem.tsx
- src/components/WalletConnect/Network/WCNetworkAvatarGroup.tsx
- src/components/common/Account/AccountActionButton/index.tsx
- src/components/common/Account/AccountActionButton/style/index.ts
- src/components/common/AvatarGroup/index.tsx
- src/components/common/Modal/ConfirmModal/index.tsx
- src/components/common/Modal/ConfirmModal/styles/index.ts
- src/components/common/Modal/DeleteModal/styles/index.ts
- src/components/design-system-ui/button/index.tsx
- src/hooks/screen/Transaction/useTransactionV2.ts
- src/screens/Home/Browser/BrowserTab.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/style/index.ts
- src/screens/Transaction/SendFundV2/Amount.tsx
> [Issue-941]: Fix bug related to WalletConnect feature

- src/hooks/screen/Home/Staking/useGetStakingList.ts
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
> [issue-955] The  of the staking item is displayed incorrectly

- src/screens/Home/Crypto/shared/Button.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
- src/utils/i18n/zh_CN.ts
> [issue-970] update receive button

- src/components/EmptyList.tsx
- src/components/EmptyValidator.tsx
- src/components/LazyFlatList.tsx
- src/predefined/dAppSites.ts
- src/screens/Home/NFT/Collection/NftCollectionList.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/Home/NFT/NFTStackScreen.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/vi_VN.ts
- src/utils/i18n/zh_CN.ts
> [Issue-927]: Allow reload NFT, staking in case list is empty

- ios/Podfile.lock
- src/components/common/Confirmation/ConfirmationGeneralInfo/index.tsx
- src/screens/Home/Crypto/BuyToken.tsx
- src/utils/permission/camera.ts
- yarn.lock
> [issue-947] Error page in case touch back when buy token

- src/components/SubHeader.tsx
- src/screens/Transaction/NFT/index.tsx
> [issue-986] Bugs related to Send NFT

- src/components/HideBalanceItem.tsx
- src/components/common/HistoryItem/index.tsx
- src/components/common/TokenGroupBalanceItem/index.tsx
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/History/index.tsx
- src/screens/Home/Staking/Balance/StakingBalanceItem.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
> [Issue-917]: Update UI - Update show/hide balance feature

- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/Login/index.tsx
Pull request for issue #444.
This commit is a hot fix for issue-444
> [issue-444] Change password affect transactions flow

- src/components/common/StakingTab/index.tsx
- src/hooks/chain/useChainChecker.ts
- src/hooks/screen/Transaction/useTransaction.ts
- src/screens/Transaction/Stake/index.tsx
> [Issue-975]: Still show popup turn on network in case change Pool to Nominate

- html/Web.bundle/site/locales/ja/translation.json
- html/Web.bundle/site/locales/ru/translation.json
- src/hooks/init/useSetupI18n.ts
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Home/History/Detail/parts/Layout.tsx
> [Issue-1027]: Do not save config language when upgrade version

- src/predefined/dAppSites.ts
- src/screens/AddProvider.tsx
- src/screens/NetworkSettingDetail.tsx
- yarn.lock
> [Issue-989]: Show incorrect provider in case import provider successful

- src/components/common/RpcSelectorModal/index.tsx
> [Issue-840]: Upgrade UI Select provider screen

- src/components/common/Modal/UnlockModal/index.tsx
- src/hooks/modal/useUnlockModal.ts
- src/routes/index.ts
- src/screens/Settings/Security/index.tsx
> [issue-1023] Show popup allows Face ID/Touch ID after sign transaction

- src/messaging/index.ts
- src/screens/MasterPassword/ApplyMasterPassword/index.tsx
- yarn.lock
> [issue-1032] Handle the case of auto lock after importing multi account

- src/components/Modal/ConnectWebsiteModal.tsx
- src/components/Modal/common/TokenSelector.tsx
- src/components/common/SelectModal/BasicSelectModal.tsx
- src/components/design-system-ui/modal/ModalBaseV2.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/screens/AddProvider.tsx
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
- src/screens/Settings/Security/index.tsx
> [Issue-1014]: Fix UI bug on Android

- src/screens/Account/AttachReadOnly/index.tsx
> [Issue-918]: Record the address entered from the view-only account screen attached to the recent address in the address book

- src/screens/Home/Crypto/CustomizationModal.tsx
> [Issue-1041]: Fix error page when open Customize access screen

- ios/Podfile.lock
- ios/SubWalletMobile.xcodeproj/project.pbxproj
- src/components/Modal/common/TokenSelector.tsx
- src/screens/AddProvider.tsx
- src/screens/Home/Crypto/shared/SelectAccAndTokenModal.tsx
- src/screens/Transaction/SendFundV2/index.tsx
- src/screens/Transaction/Stake/index.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/ja_JP.ts
- src/utils/i18n/ru_RU.ts
- src/utils/i18n/vi_VN.ts
- src/utils/i18n/zh_CN.ts
- yarn.lock
> [Issue-995]: Fix bug navigate incorrect in case search token to get address

- src/screens/MasterPassword/Login/index.tsx
> [issue-1020] Need to auto-focus the master password field on Android device

- src/utils/account.ts
> [issue-1016] Biometric failed attempts alert isn't shown in enable biometric/change master password

- src/screens/Confirmations/parts/Sign/Evm.tsx
- src/screens/Confirmations/parts/Sign/Substrate.tsx
- src/screens/Home/Browser/BrowserTab.tsx
- src/screens/Home/index.tsx
- src/utils/deeplink/index.ts
> [Issue-1019]: Auto back to App previous in case connect wallet connect the fisrt times in app Browser

- src/screens/Home/index.tsx
> [issue-1051] Re-check bug static server to support cors

- android/app/src/main/AndroidManifest.xml
- src/AppNavigator.tsx
- src/AppNew.tsx
- src/routes/home.ts
- src/routes/index.ts
- src/routes/staking/stakingScreen.ts
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/StakingScreen.tsx
- src/screens/Home/index.tsx
- src/utils/deeplink/index.ts
> [Issue-1049]: Improve deeplink (Add more deeplink type)

- src/screens/Home/NFT/Detail/NftDetail.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/ja_JP.ts
- src/utils/i18n/ru_RU.ts
- src/utils/i18n/vi_VN.ts
- src/utils/i18n/zh_CN.ts
> [Issue-961]: Show collection ID and NFT Id in the NFT detail screen for mobile app

- src/components/Scanner/SignatureScanner.tsx
> [Issue-1059]: Update UI Scan QR in case sign transaction use Polkadotvault

- src/hooks/screen/Home/Crypto/useBuyToken.ts
> [Issue-1053]: Handle the case of supporting multiple services when buy token

- src/constants/buy/token.ts
- src/stores/index.ts
Pull request for issue #1074 #1076
> [issue-1074, issue-1076] Cache the dApp list when opening the app for the first time. Update buy token ordering

- src/components/Field/PoolSelector/index.tsx
- src/components/Field/ValidatorSelector/index.tsx
- src/components/Modal/common/PoolSelector.tsx
> [Issue-1079]: Hide the AutoSelect validator/collator/dApp button if this method is not supported on mobile app

- src/screens/Account/AccountsScreen/index.tsx
> [Issue-1071]: Fix bug navigate incorrect in case switch account

- src/screens/Confirmations/variants/Transaction/variants/TransferBlock.tsx
- src/utils/i18n/en_US.ts
- src/utils/i18n/ja_JP.ts
- src/utils/i18n/ru_RU.ts
- src/utils/i18n/vi_VN.ts
- src/utils/i18n/zh_CN.ts
> [Issue-843]: Add the warning message in case XCM transfer

- src/screens/Confirmations/variants/AddNetworkConfirmation/index.tsx
- src/screens/Confirmations/variants/AddNetworkConfirmation/styles/index.ts
- src/screens/ImportNetwork.tsx
> [Issue-813]: Still allow add network from dApp in case cannot connect to this provider

- src/screens/Transaction/helper/nftParamsHandler.ts
> [Issue-1088]: Fix bug can not Send Sub0 NFT

- src/components/common/SelectAccountItem/index.tsx
- src/components/design-system-ui/button/index.tsx
- src/screens/Account/AccountsScreen/index.tsx
> [issue-1066]: Swipe to delete/copy account

- .github/workflows/build-release.yml
- .github/workflows/test-android.yml
- android/app/build.gradle
- src/components/TokenSelectItem.tsx
- src/components/common/SelectModal/parts/TokenSelectItem.tsx
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/Tokens/ConfigureToken.tsx
> [issue-1097] Add Token Name to the Token Details and Import Token screen for mobile app

- src/components/WalletConnect/Account/WCAccountSelect.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Confirmations/variants/ConnectWalletConnectConfirmation/index.tsx
> [issue-1110] Update message on the Create on account

- src/constants/nft.ts
- src/screens/Home/NFT/Detail/NftDetail.tsx
> [issue-295] Support 3D NFT display

- src/components/Modal/ConnectWebsiteModal.tsx
> [issue-1115] Still enable "Confirm" button although do not select account in case reconnect after unblock dApp

- src/hooks/screen/Transaction/useTransactionV2.ts
- src/screens/Confirmations/parts/Detail/Substrate/Transaction.tsx
- src/utils/i18n/en_US.json
> [issue-1122] Crash app in case select token when send fund

- src/components/Modal/ConnectWebsiteModal.tsx
- src/components/common/ForgotPasswordModal/index.tsx
- src/screens/Account/AccountsScreen/index.tsx
> [issue-1108] Fix some UI bug on Android

- src/hooks/chain/useChainAssets.ts
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/hooks/screen/ImportNft/useGetContractSupportedChains.ts
- src/hooks/screen/Staking/useGetSupportedStakingTokens.ts
- src/hooks/screen/useTokenGroup.ts
- src/screens/Tokens/index.tsx
- src/screens/Transaction/SendFundV2/index.tsx
> [issue-1133] Hide the token of the Inactive chain on mobile app

- src/components/common/Modal/ConfirmModal/index.tsx
- src/hooks/screen/Transaction/useTransaction.ts
- src/hooks/screen/Transaction/useTransactionV2.ts
- src/providers/AppModalContext.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
- yarn.lock
> [issue-1136] Update text on Enable network screen

- src/components/common/Confirmation/ConfirmationGeneralInfo/index.tsx
> [Issue-980] Follow up show dApp's logo in svg in Browser and dApp confirmations

- src/components/common/SelectModal/index.tsx
> [issue-1143] Show duplicate popup Enable network

- .github/workflows/build-internal.yml
- src/components/Modal/AddressBook/ReadonlyAddressField.tsx
- src/hooks/common/useCopyClipboard.ts
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Confirmations/variants/AddNetworkConfirmation/index.tsx
- src/screens/Home/Crypto/ReceiveModal.tsx
- src/screens/Tokens/ConfigureToken.tsx
> [issue-1130] Fix some UI bug on Android

- ios/Podfile.lock
- src/AppNavigator.tsx
- src/components/Input/InputAmount/style/index.ts
- src/hooks/screen/Transaction/useTransactionV2.ts
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFundV2/index.tsx
- src/screens/Transaction/Stake/index.tsx
- src/screens/Transaction/TransactionDone/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
> [issue-1121] Migrate useTransaction from v1 to v2

- ios/SubWalletMobile.xcodeproj/project.pbxproj
- src/AppNew.tsx
- src/constants/index.ts
- src/hooks/screen/Home/Crypto/useShowBuyToken.ts
- src/screens/Home/Browser/index.tsx
- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/Home/index.tsx
- src/stores/base/Settings.ts
- src/stores/types.ts
> [issue-1179] Update rtk query with fetch for Buy Token

- src/providers/WebRunnerProvider/WebRunner.tsx
> [issue-1157] Bug reset data on version IOS 17.1.1

- src/components/MissionPoolHorizontalItem/index.tsx
- src/components/MissionPoolItem/index.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolDetailModal/MissionPoolDetailModal.tsx
> [issue-1189] Unable to show list dApp, mission pool when see all on Android

- src/AppNew.tsx
- src/providers/WebRunnerProvider/WebRunner.tsx
> [issue-1190] Add Update webview popup in case Android app takes forever to load

- src/components/Input/InputCheckBox.tsx
- src/components/Modal/GeneralTermModal/index.tsx
- src/components/common/DownloadSeedPhraseModal/index.tsx
- src/components/design-system-ui/alert-box/index.tsx
- src/constants/termAndCondition.ts
- src/screens/Account/CreateAccount/InitSecretPhrase.tsx
- src/screens/Account/CreateAccount/TnCSeedPhraseModal.tsx
- src/screens/Account/CreateAccount/VerifySecretPhrase.tsx
- src/screens/Account/CreateAccount/index.tsx
- src/screens/Home/FirstScreen.tsx
- src/screens/Home/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/style/index.ts
- src/utils/i18n/en_US.json
> [Issue-1197] Update T&C

- src/hooks/screen/Home/Crowdloans/useGetCrowdloanList.ts
- src/screens/Home/Crowdloans/CrowdloanItem.tsx
- src/screens/Home/Crowdloans/index.tsx
- src/types/index.ts
- src/utils/fetchStaticData.ts
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1209]: Update missing crowdloan chains on mobile app

- src/components/Input/InputAddress.tsx
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
> [issue-1227]: Fix bug do not display contract address in case scan QR when import NFT, token

- src/components/AccountTokenDetail/index.tsx
- src/components/AccountTokenDetail/style/index.ts
- src/components/MetaInfo/index.tsx
- src/components/MetaInfo/parts/NumberItem.tsx
- src/components/MetaInfo/shared.tsx
- src/components/MetaInfo/style/index.ts
- src/components/Modal/GeneralTermModal/index.tsx
- src/components/design-system-ui/tab/index.tsx
- src/components/design-system-ui/tab/style/index.ts
- src/screens/Home/Crypto/TokenDetailModal.tsx
> [issue-1095]: Update the Token detail screen for mobile app

- ios/Podfile.lock
- package.json
- src/constants/index.ts
- src/screens/Home/Staking/StakingDetail/StakingDetailModal/index.tsx
- src/screens/Settings/index.tsx
- src/screens/Transaction/TransactionDone/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
- yarn.lock
> [issue-1216]: Add pop-up to request rating on mobile app

- src/routes/index.ts
- src/screens/Settings/WalletConnect/ConnectionDetail.tsx
- src/screens/Settings/WalletConnect/ConnectionList.tsx
> [issue-1198] Fix bug crash app when accept Camera on Android

- package.json
- src/components/Modal/GeneralTermModal/index.tsx
- src/hooks/static-content/useGetDAppList.ts
- yarn.lock
> [issue-1211] Apply static content for T&C

- src/components/Modal/GeneralTermModal/index.tsx
- src/screens/Home/Staking/Balance/StakingBalanceList.tsx
- src/screens/Home/Staking/InstructionModal/InstructionItem/index.tsx
- src/screens/Home/Staking/InstructionModal/index.tsx
- src/screens/Transaction/Stake/index.tsx
> [issue-1215] Fix bug show popup instruction when staking nominate for Vara Network

- src/components/LazySectionList.tsx
- src/components/Modal/common/ChainSelector.tsx
- src/hooks/balance/useGetBalance.ts
- src/hooks/common/useLazyList.ts
- src/hooks/history/index.tsx
- src/hooks/history/useHistorySelection.tsx
- src/hooks/screen/Transaction/useTransactionV2.ts
- src/messaging/index.ts
- src/routes/index.ts
- src/screens/Home/History/index.tsx
- src/screens/Home/History/parts/HistoryAccountSelector.tsx
- src/screens/Home/History/parts/HistoryChainSelector.tsx
- src/screens/Transaction/TransactionDone/index.tsx
- PR for #1207 
- This PR may fix #1232
> [issue-1207] Update history feature

- src/screens/Settings/index.tsx
> [issue-1245] Add default subject in email feedback in app

- src/assets/checkbox.svg
- src/components/Modal/GeneralTermModal/index.tsx
- src/components/design-system-ui/button/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/style/index.ts
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/style/index.ts
> [issue-1211] Add Alert in case user do not check Checkbox

- src/AppNavigator.tsx
> [issue-1221] Fix bug automatically switch all accounts mode when connect or perform transaction via WalletConnect

- src/hooks/screen/Home/Staking/useGetStakingList.ts
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
> [issue-1255] Fix bug error page when reset account

- src/assets/checkbox-with-border.svg
- src/assets/checkbox.svg
- src/assets/index.ts
- src/components/Input/InputCheckBox.tsx
- src/components/Modal/GeneralTermModal/index.tsx
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
> [issue-1254] Fix UI bug Filter screen

- src/hooks/balance/useGetBalance.ts
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Transaction/SendFundV2/index.tsx
> [issue-1224] Update UX in case transfer all

- src/components/Modal/GeneralTermModal/index.tsx
- src/constants/termAndCondition.ts
> [issue-1276] Fallback t&c content incase static content offline

- src/components/HideBalanceItem.tsx
- src/components/common/HistoryItem/index.tsx
- src/screens/Home/History/Detail/parts/Layout.tsx
- src/screens/Home/History/index.tsx
- src/screens/Transaction/TransactionDone/index.tsx
Pull request for issue #1263 and  #1283
> [issue-1263] Do not show Transfer NFT history details (on all account mode) - Bug related to EVM history

- src/screens/Settings/WalletConnect/ConnectionList.tsx
- src/utils/permission/camera.ts
> [issue-1267] Fix bugs related to Access Camera permission when usingWalletConnect feature

- src/hooks/campaign/useGetBannerByScreen.ts
- src/screens/Home/Crowdloans/CampaignBannerModal/index.tsx
- src/utils/storage.ts
> [issue-1291] Add flag 'not show again' for MKT Campaign when resetting event iOS 17 is triggered

- src/constants/index.ts
- src/screens/Account/ConnectQrSigner/ConnectKeystone.tsx
- src/screens/Account/ConnectQrSigner/ConnectParitySigner.tsx
- src/screens/Account/ConnectQrSigner/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1261] Add hyperlink when connect Polkadot Vault

- src/hooks/chain/useChainChecker.ts
- src/hooks/screen/Home/Crypto/useBuyToken.ts
- src/hooks/screen/Transaction/useTransaction.ts
- src/screens/Home/Crypto/BuyToken.tsx
- src/screens/Transaction/Stake/index.tsx
> [issue-1144] Add requires enable network in case select token when buy token

- src/screens/Home/Browser/BrowserTab.tsx
> [issue-1173] Fix bug do not dowload seedPhrase from web.subwallet.app in webview

- src/screens/Transaction/Stake/index.tsx
> [issue-1144] Fix bug crash app when Stake from All account

- src/components/MissionPoolHorizontalItem/MissionPoolFooter.tsx
- src/components/MissionPoolHorizontalItem/index.tsx
- src/components/MissionPoolHorizontalItem/style.ts
- src/components/design-system-ui/badge/index.tsx
- src/components/design-system-ui/badge/styles/index.ts
- src/components/design-system-ui/index.ts
- src/screens/Home/Browser/BrowserHome.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolDetailModal/MissionPoolDetailModal.tsx
- src/screens/Settings/index.tsx
> [issue-1280] Update new layout for mission pool

- src/utils/storage.ts
> [issue-1330] Implement auto recover on android and ios lower than 17

- ios/Podfile.lock
- src/components/Modal/GeneralTermModal/index.tsx
- src/screens/Home/FirstScreen.tsx
- src/screens/MasterPassword/ChangeMasterPassword/index.tsx
- src/screens/MasterPassword/CreateMasterPassword/index.tsx
- src/screens/Settings/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
- yarn.lock
Pull request for issue #1340 #1347
> [issue-1340] Do not show message in case send VARCH token - Add support i18n for T&C popup's label

- src/AppNavigator.tsx
- src/routes/earning.ts
- src/screens/Home/Earning/PositionDetail/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
- src/screens/Transaction/Earn/index.tsx
> [issue-1251] Update deeplink for Earning feature

- ios/Podfile.lock
- src/hooks/campaign/useGetBannerByScreen.ts
- src/screens/Home/Crowdloans/CampaignBannerModal/index.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/utils/storage.ts
> [issue-1346] Add banner in token detail

- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/hooks/common/useLazyList.ts
- src/hooks/earning/useGroupYieldPosition.ts
- src/hooks/earning/useYieldGroupInfo.ts
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/List/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
> [issue-1251] Improve performance Earning feature

- src/screens/Home/Browser/BrowserOptionModal.tsx
- src/screens/Home/Browser/BrowserTab.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1338] Add desktop mode for dapp browser

- src/components/Earning/EarningRewardInfo/index.tsx
- src/components/Modal/Earning/EarningNominationModal/index.tsx
- src/components/Modal/Earning/EarningNominationModal/style.ts
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Confirmations/variants/Transaction/variants/ClaimReward.tsx
Pr for issue #1352 #1353 #1354
> [issue-1253] Fix some UI bug for Earning feature

- src/utils/storage.ts
> [issue-1381] Re-check bug reset data on IOS 17

- src/components/Browser/BookmarkItem.tsx
- src/components/Browser/BrowserItem.tsx
- src/screens/Home/Browser/BrowserHome.tsx
- src/screens/Home/Browser/Shared/BookmarkSection.tsx
- src/screens/Home/Browser/Shared/HistorySection.tsx
- src/screens/Home/Browser/Shared/IconItem.tsx
- src/screens/Home/Browser/Shared/RecommendSection.tsx
- src/screens/Home/Browser/Shared/SectionHeader.tsx
- src/screens/Home/Crowdloans/index.tsx
Pull request for issue #1152 #1296
> [issue-1152] Improve performance Browser - [issue-1296] Add swipe down to reload in Crowdloan tab

- src/hooks/static-content/useShowBuyToken.ts
> [issue-1374] Fix bug Android can't show Buy and Browser tab

- android/app/src/main/AndroidManifest.xml
- src/AppNavigator.tsx
> [issue-1373] Fix bug cannot connect WalletConnect from external Browser

- src/components/Modal/IntroducingModal/index.tsx
- src/components/Modal/IntroducingModal/style.ts
- src/hooks/campaign/useGetBannerByScreen.ts
- src/screens/Home/Crowdloans/index.tsx
- src/screens/Home/index.tsx
> [issue-1388] Add a temporary popup to introduce the earning feature

- src/components/design-system-ui/alert-box/base/index.tsx
- src/hooks/account/usePreCheckAction.ts
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/Earn/index.tsx
- src/screens/Transaction/helper/earning/base.ts
- src/screens/Transaction/parts/FreeBalance.tsx
- src/screens/Transaction/parts/FreeBalanceToEarn.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1368] Fix some Earning UI bug

- src/components/Browser/BrowserItem.tsx
- src/hooks/screen/Home/Browser/DesktopMode/useGetDesktopMode.ts
- src/hooks/static-content/useGetDAppList.ts
- src/screens/Home/Browser/BrowserOptionModal.tsx
- src/screens/Home/Browser/BrowserTab.tsx
- src/stores/Browser.ts
- src/stores/types.ts
- src/types/browser.ts
> [issue-1371] Improve desktop mode for dApp browser

- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
- src/screens/Transaction/Earn/index.tsx
> [issue-1399] Bug performance on Start eanring screen with direct nomination

- src/screens/Home/index.tsx
> [issue-1410] Add popup want to user claim reward when Astar update dApp staking v3

- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Home/Browser/MissionPool/MissionPoolDetailModal/MissionPoolDetailModal.tsx
- src/screens/Transaction/Unbond/index.tsx
> [issue-1401] Add Rating pop-up for Fast Unstake action

- src/screens/Home/History/index.tsx
> [issue-1345] Fix bug of history filter

- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/constants/earning/EarningDataRaw.ts
- src/screens/Transaction/Earn/index.tsx
- src/screens/Transaction/Unbond/index.tsx
> [issue-1362] Update wait time for Liquid staking

- src/screens/Home/Earning/PositionList/index.tsx
> [issue-1379] Add CTA Earn now on the PositionList screen

- src/components/Earning/EarningRewardInfo/index.tsx
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
> [issue-1372] Fix UI bug for EarningPoolDetailModal

- src/screens/Home/Earning/List/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
> [issue-1405] Fix bug reload Your earning positions screen

- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
- src/screens/Transaction/Earn/index.tsx
> [issue-1427] Error page on Earning screen

- src/screens/Home/Earning/List/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
> [issue-1433] Improve navigation and animation PositionList and GroupList when Change Account or Pull to Refresh

- src/screens/Home/History/shared.ts
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1396] Add time-out status for transaction history

- src/components/Item/Earning/EarningGroupItem/index.tsx
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
- src/types/earning.ts
> [issue-1440] Fix bug alert popup display continuously when turn on chain in earning pool

- src/hooks/screen/Home/useGetChainSlugs.ts
> [issue-1442] Show incorrect tokens on the balance screen in case an account with the type 'ed25519' is imported

- src/screens/Transaction/Earn/index.tsx
> [issue-1424] Add alert warning when user select yy validator although re-commended xx validators (xx > yy)

- src/screens/Home/Earning/List/index.tsx
- src/screens/Home/index.tsx
> [issue-1439] [Earning] Handle the case of switch tab on menu

- src/components/QrCodeScanner.tsx
> [issue-1350] Fix bug Tooltip button doesn't work

- src/components/Item/Earning/EarningGroupItem/index.tsx
- src/components/Item/Earning/EarningInfoItem/index.tsx
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PositionList/index.tsx
- src/screens/Transaction/Earn/index.tsx
- src/utils/earning.ts
> [issue-1455] Update position and options actions for Astar Staking DApp

- src/screens/Confirmations/variants/EvmTransactionConfirmation/index.tsx
- src/screens/Confirmations/variants/Transaction/variants/TransferBlock.tsx
- src/screens/Transaction/SendFund/index.tsx
> [Issue-1459] Update UI when transfer token for EVM chains

- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PositionDetail/index.tsx
> [issue-1461] Bug failed to get data when stake more from position details screen

- src/components/FlatListScreen.tsx
- src/hooks/useFilterModal.ts
- src/screens/Home/Earning/GroupList/index.tsx
> [issue-1465] Setup default filter on earning options screen

- src/components/Earning/EarningPoolInfo/index.tsx
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Transaction/Earn/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1463] Update content for earning feature

- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
> [issue-1225] Disable button Continue if do not load Available balance

- src/components/EmptyList.tsx
- src/screens/Home/Crypto/TokenDetailModal.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1235] Update the Token details screen for mobile app

- src/hooks/screen/Home/Crowdloans/useGetCrowdloanList.ts
- src/stores/feature/common/ChainInfoMap.ts
- src/stores/index.ts
> [issue-1448] Flash screen when re-open Crowdloans tab

- src/screens/Home/index.tsx
> [issue-1481] Turn off popup Dapp staking

- src/screens/Home/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [issue-1485] Update tabbar's content

- src/components/Browser/BrowserItem.tsx
- src/components/MissionPoolHorizontalItem/index.tsx
- src/screens/Home/Browser/BrowserHome.tsx
- src/screens/Home/Browser/Shared/MissionPoolSection.tsx
- src/screens/Settings/index.tsx
> [issue-1488] Move mission pool into dApp browser

- src/AppNavigator.tsx
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
- src/components/Modal/common/AccountSelector.tsx
- src/components/Modal/common/CancelUnstakeSelector.tsx
- src/components/Modal/common/NominationSelector.tsx
- src/components/Modal/common/PoolSelector.tsx
- src/components/Modal/common/TokenSelector.tsx
- src/components/Modal/common/ValidatorSelector.tsx
- src/components/WalletConnect/Account/WCAccountSelect.tsx
- src/components/WalletConnect/Network/WCNetworkSelected.tsx
- src/components/WalletConnect/Network/WCNetworkSupported.tsx
- src/components/design-system-ui/modal/ModalBaseV2.tsx
- src/components/design-system-ui/modal/SwFullSizeModal.tsx
- src/components/design-system-ui/modal/SwModal.tsx
- src/screens/Account/CreateAccount/TnCSeedPhraseModal.tsx
- src/screens/Account/CreateAccount/index.tsx
- src/screens/Home/Crypto/TokenSearchModal.tsx
> [issue-1444] Add action close modal when click back virtual button

- src/App.tsx
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/constants/earning/EarningDataRaw.ts
- src/hooks/static-content/useGetEarningStaticData.ts
- src/hooks/static-content/useGetTermAndConditionData.ts
- src/screens/Transaction/Unbond/index.tsx
> [issue-1365] Improve StaticContent for Earning

- src/components/Input/InputText.tsx
- src/screens/ImportToken/ImportToken.tsx
- src/screens/Tokens/ConfigureToken.tsx
> [issue-1407] Fix UI bug in TokenDetail screen

- src/components/Modal/common/TokenSelector.tsx
- src/components/TokenSelectItem.tsx
- src/components/common/CancelUnstakeItem/index.tsx
- src/components/common/SelectModal/index.tsx
- src/components/common/SelectModal/parts/TokenSelectItem.tsx
- src/hooks/screen/Staking/useGetSupportedStakingTokens.ts
- src/hooks/screen/useAccountBalance.ts
- src/screens/Home/Crypto/BuyToken.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/Stake/index.tsx
- src/types/balance.ts
- src/utils/sort/token.ts
> [issue-1234] Sort the token by the balance on mobile app

- src/screens/Home/Browser/BrowserOptionModal.tsx
- src/screens/Home/Browser/BrowserTab.tsx
> [issue-1492] Turn off userAgent when desktop mode is disabled

- src/components/common/ErrorFallbackScreen/index.tsx
- src/components/common/ErrorFallbackScreen/style/index.tsx
- src/screens/Settings/General/index.tsx
> [issue-1500] Update Error screen, recommend upload crash log

- src/AppNavigator.tsx
- src/screens/Home/index.tsx
- src/stores/base/Settings.ts
- src/stores/types.ts
- src/stores/utils/index.ts
> [issue-1295] Fix bug display MKT campaign on Apply master password screen

- src/components/MissionPoolHorizontalItem/MissionPoolStatusTag.tsx
- src/hooks/useMissionPools.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolDetailModal/MissionPoolDetailModal.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolsByCategory.tsx
> [issue-1511] Auto detect mission pool status by timeline

- src/components/Earning/EarningBaseInfo/parts/EarningAccountInfo/index.tsx
- src/components/Earning/EarningBaseInfo/parts/EarningNominationInfo/index.tsx
- src/components/Earning/EarningPoolInfo/index.tsx
- src/components/Earning/EarningRewardInfo/index.tsx
- src/components/Earning/EarningWithdrawMeta/index.tsx
- src/components/Item/Earning/EarningPoolItem/index.tsx
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/hooks/earning/useGetPoolTargetList.ts
- src/hooks/earning/useYieldRewardTotal.ts
- src/screens/Confirmations/variants/Transaction/variants/ClaimReward.tsx
- src/screens/Confirmations/variants/Transaction/variants/Withdraw.tsx
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionDetail/index.tsx
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
- src/screens/Transaction/helper/earning/earningHandler.ts
> [issue-1517] Bug pool info is undefined

- src/screens/Settings/index.tsx
> [issue-1542] Navigation support users by platform

- src/screens/Home/Crypto/TokenDetailModal.tsx
> [issue-1529] Fix bug do not show account on the Accounts token details screen in case all balance is locked

- src/screens/Home/Crypto/TokenGroupsDetailUpperBlock.tsx
- src/screens/Home/Crypto/TokenGroupsUpperBlock.tsx
- src/screens/Home/Crypto/shared/Button.tsx
> [issue-1541] Add Swap button

- src/components/Field/PoolSelector/index.tsx
- src/components/Item/Earning/EarningGroupItem/index.tsx
- src/components/Item/Earning/EarningInfoItem/index.tsx
- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/Tag/EarningTypeTag/index.tsx
- src/hooks/earning/useYieldGroupInfo.ts
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
> [issue-1560] Improve UX UI for earning feature

- src/routes/earning.ts
- src/screens/Home/Earning/GroupList/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
> [Issue-1562] Fix bug doo not show token earning option of MAnta network

- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/SendFund/styles/index.ts
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [Issue-1571] Add warning message for cross chain transfer to an exchange (CEX)

- src/components/Modal/Earning/EarningPoolSelector/index.tsx
> [Issue-1604] Set default pool for Vara network, Avail Turing

- src/screens/Transaction/Earn/index.tsx
> [Issue-1549] Fix bug error page cannot read property priceId of undefined

- src/components/Field/PoolSelector/index.tsx
- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/common/SelectModal/index.tsx
- src/constants/stakingScreen.ts
> [Issue-1565] Update tag Recommend for SubWallet's pool

- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
> [Issue-1601] Fix bug do not show message error in select many validators

- src/components/StaticContent/ContentGenerator/index.tsx
- src/components/common/Modal/GlobalModal/index.tsx
- src/hooks/static-content/useHandleAppBannerMap.ts
- src/hooks/static-content/useHandleAppConfirmationMap.ts
- src/hooks/static-content/useHandleAppPopupMap.ts
- src/providers/AppOnlineContentProvider.tsx
- src/types/staticContent.ts
> [Issue-1546] Update Marketing Campaign mechanism 9 minutes ago

- src/components/design-system-ui/modal/SwFullSizeModal.tsx
- src/components/design-system-ui/modal/SwModal.tsx
> [Issue-1618] Modal and popup are overlapping in some cases

- src/screens/Home/Browser/MissionPool/MissionPoolsByCategory.tsx
- src/screens/Home/Browser/Shared/MissionPoolSection.tsx
- src/screens/Settings/index.tsx
- src/stores/utils/index.ts
> [Issue-1631] Handle fallback for Mission Pools

- src/App.tsx
- src/components/Modal/RemindBackupModal/index.tsx
- src/components/common/SelectExportType/index.tsx
- src/constants/index.ts
- src/screens/Account/AccountExport/styles/index.ts
> [Issue-1282] Fix bug spam Lockscreen

- src/screens/Home/Crypto/CustomizationModal.tsx
> [Issue-1625] Fix bug do not show custom network on Customize asset display screen

- src/hooks/chain/useChainInfoData.tsx
- src/hooks/screen/ImportNft/useGetFungibleContractSupportedChains.ts
- src/hooks/screen/ImportNft/useGetNftContractSupportedChains.ts
- src/screens/ImportToken/ImportNft.tsx
- src/screens/ImportToken/ImportToken.tsx
> [Issue-1644] Support GRC-20 token

- android/app/src/main/AndroidManifest.xml
- src/screens/Home/Browser/BrowserTab.tsx
> [Issue-1657] Support using camera in Dapps for Android

- src/providers/WebRunnerProvider/WebRunner.tsx
> [Issue-1661] Add fallback web-runner

- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
- src/components/Modal/common/PoolSelectorDetailModal.tsx
- src/components/Modal/common/ValidatorSelectorDetailModal.tsx
- src/components/common/StakingPoolItem/index.tsx
- src/components/common/StakingPoolItem/style/index.ts
- src/constants/stakingStatusUi.ts
- src/hooks/screen/Staking/useGetValidatorList.ts
- src/types/earning.ts
> [Issue-1536] Implement UI for EarningPoolSelector

- src/components/FlatListScreen.tsx
- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/Modal/Earning/EarningValidatorSelector/index.tsx
- src/components/Search.tsx
- src/components/design-system-ui/badge/DotBadge/index.tsx
- src/components/design-system-ui/badge/DotBadge/styles/index.ts
- src/hooks/screen/Home/useGetChainSlugs.ts
- src/hooks/screen/useIsValidNetwork.ts
- src/hooks/transaction/useHandleSubmitTransaction.ts
- src/screens/Confirmations/variants/Transaction/variants/Bond.tsx
- src/screens/Transaction/Earn/index.tsx
> [Issue-1473] Fix bug related to Earning feature

- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionDetail/index.tsx
> [Issue-1660] Remove Parallel liquid staking

- src/hooks/static-content/useGetConfig.ts
- src/screens/EarningPreview/EarningPreviewPools/index.tsx
- src/screens/Home/Earning/PositionDetail/index.tsx
> [Issue-1671] Disable button Stake with Liquid staking Parallel

- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/common/AvatarGroup/index.tsx
- src/components/common/SelectAccountItem/index.tsx
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Account/ExportAllAccount/index.tsx
- src/screens/Account/RestoreJson/index.tsx
- src/screens/Account/RestoreJson/styles/index.ts
- src/screens/Confirmations/variants/ConnectWalletConnectConfirmation/index.tsx
> [Issue-1641] Fix some UI bug

- src/components/Payload/DisplayPayload.tsx
- src/components/Scanner/QrAddressScanner.tsx
- src/constants/qr.ts
- src/hooks/account/useGetAccountTitleByAddress.ts
- src/hooks/account/usePreCheckAction.ts
- src/screens/Account/ConnectQrSigner/index.tsx
- src/screens/Confirmations/index.tsx
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/Swap/index.tsx
- src/screens/Transaction/Unbond/index.tsx
- src/screens/Transaction/Withdraw/index.tsx
- src/types/qr/scanner.ts
> [Issue-1639] Add message when perform connect and sign transaction with Moonbeam on Polkadot vault

- src/hooks/common/useGetChainSlugsByCurrentAccount.ts
- src/hooks/earning/useYieldGroupInfo.ts
> [Issue-1650] Still show earning options when hide chain online

- src/components/common/BannerSlider/index.tsx
- src/hooks/static-content/useHandleAppBannerMap.ts
- src/hooks/static-content/useHandleAppConfirmationMap.ts
- src/hooks/static-content/useHandleAppPopupMap.ts
- src/providers/AppOnlineContentProvider.tsx
- src/providers/DataContext.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolSearchByTabView/MissionPoolSearchByType.tsx
- src/screens/Home/Browser/MissionPool/MissionPoolsByCategory.tsx
- src/screens/Home/Browser/MissionPool/context.ts
- src/screens/Home/Browser/MissionPool/index.tsx
- src/screens/Home/Browser/MissionPool/types.ts
- src/screens/Home/index.tsx
- src/screens/WebViewDebugger.tsx
- src/types/staticContent.ts
> [Issue-1690] Improve Mission Pool

- src/components/common/BannerSlider/index.tsx
- src/hooks/static-content/useHandleAppBannerMap.ts
- src/hooks/static-content/useHandleAppConfirmationMap.ts
- src/hooks/static-content/useHandleAppPopupMap.ts
- src/providers/AppOnlineContentProvider.tsx
- src/providers/DataContext.tsx
- src/types/staticContent.ts
> [Issue-1546] Add some features of marketing campain ( Phrase 3)

- src/AppNavigator.tsx
- src/components/Header.tsx
- src/routes/index.ts
- src/routes/transaction/transactionAction.ts
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenGroupsDetail.tsx
- src/screens/Transaction/SendFund/OldSendFund/index.tsx
- src/screens/Transaction/TransactionScreen.tsx
> [Issue-1707] Fix bug Cannot set property 'status' of undefined in ios device with ios < 16.4

- src/components/Item/Swap/ChooseFeeItem.tsx
- src/components/Modal/Swap/ChooseFeeTokenModal.tsx
- src/components/common/Account/AccountSelectField/index.tsx
- src/components/common/SelectAccountItem/index.tsx
- src/components/common/SelectExportType/index.tsx
- src/hooks/account/useAccountAvatarInfo.ts
- src/hooks/account/useAccountRecoded.ts
- src/hooks/account/useIsMantaPayEnabled.ts
- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/providers/DataContext.tsx
- src/screens/Confirmations/index.tsx
- src/stores/feature/MantaPay.ts
- src/stores/index.ts
- src/stores/types.ts
- src/stores/utils/index.ts
- src/types/signer.ts
- src/utils/account.ts
- src/utils/i18n/en_US.json
> [Issue-1675] Update UI Ledger account on Mobile

- src/screens/EarningPreview/EarningPreviewPools/index.tsx
- src/screens/Home/Earning/PoolList/index.tsx
- src/screens/Home/Earning/PositionDetail/index.tsx
> [Issue-1688] Remove Interlay lending

- src/screens/Transaction/Withdraw/index.tsx
> [Issue-1712] Fix bug cannot read property 'type' of undefined

- src/components/Modal/Earning/EarningPoolSelector/index.tsx
- src/components/common/StakingPoolItem/index.tsx
- src/constants/stakingStatusUi.ts
- src/screens/Transaction/Swap/index.tsx
- src/types/earning.ts
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [Issue-1686] Update UI for blocked pool

- src/components/AccountTokenDetail/index.tsx
- src/screens/Home/Crypto/TokenDetailModal.tsx
> [Issue-1643] Add the "View on explorer" button on the Token details screen

- src/AppNavigator.tsx
- src/components/WalletConnect/Network/AddNetworkWCModal.tsx
- src/hooks/wallet-connect/useSelectWalletConnectAccount.ts
- src/routes/index.ts
- src/screens/Confirmations/variants/ConnectWalletConnectConfirmation/index.tsx
- src/screens/ImportNetwork.tsx
- src/utils/fetchNetworkByChainId.ts
> [Issue-1723] Fix bug connecting to uquid dapp with Wallet Connect

- src/screens/Transaction/Earn/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/Unbond/index.tsx
> [Issue-1736] Fix bug right operand of 'in' is not an object in Earning screen

- src/components/WalletConnect/Network/AddNetworkWCModal.tsx
- src/screens/Confirmations/variants/ConnectWalletConnectConfirmation/index.tsx
> [Issue-1738] Crash app in case connect WalletConnect on Android

- android/build.gradle
> [Issue-1727] Update target API level for Android App

- src/hooks/useHandleInternetConnectionForConfirmation.ts
- src/screens/Confirmations/parts/Sign/Evm.tsx
- src/screens/Confirmations/parts/Sign/Substrate.tsx
- src/screens/Confirmations/variants/AddNetworkConfirmation/index.tsx
- src/screens/Confirmations/variants/AddTokenConfirmation/index.tsx
- src/screens/Confirmations/variants/AuthorizeConfirmation/index.tsx
- src/screens/Confirmations/variants/ConnectWalletConnectConfirmation/index.tsx
- src/screens/Confirmations/variants/MetadataConfirmation/index.tsx
- src/utils/i18n/en_US.json
- src/utils/i18n/ja_JP.json
- src/utils/i18n/ru_RU.json
- src/utils/i18n/vi_VN.json
- src/utils/i18n/zh_CN.json
> [Issue-1171] Handle the case of disconnect internet but still click Approve

- src/screens/Confirmations/parts/Detail/Substrate/Transaction.tsx
> [Issue-1734] Error page in case click View details on the Sign transaction from dApp

- ios/Podfile.lock
- ios/SubWalletMobile.xcodeproj/project.pbxproj
- package.json
- src/hooks/static-content/useHandleAppBannerMap.ts
- src/hooks/static-content/useHandleAppPopupMap.ts
- yarn.lock
> [Issue-1735] Add condition location for App banner, App popup

- src/AppNavigator.tsx
- src/screens/Home/NFT/Item/NftItemList.tsx
- src/screens/Transaction/Swap/index.tsx
> [Issue-1151] Improve deeplink(Add more deeplink type) (Round 3)

- src/components/Header.tsx
- src/components/Input/InputAddress.tsx
- src/components/Input/InputConnectUrl.tsx
- src/components/Signing/QR/QrRequest.tsx
- src/hooks/common/useCheckCamera.ts
- src/hooks/qr/useModalScanner.ts
- src/screens/Confirmations/parts/Qr/DisplayPayload/DisplayPayloadModal.tsx
- src/screens/Settings/WalletConnect/ConnectionList.tsx
- src/utils/permission/camera.ts
> [Issue-1417] Handling Access Permission for Camera

- src/hooks/screen/useGetAvatarSubIcon.ts
- src/providers/GlobalModalContext.tsx
- src/providers/WebRunnerProvider/WebRunner.tsx
- src/screens/Account/ExportAllAccount/index.tsx
- src/screens/Home/Browser/BrowserTab.tsx
- src/screens/Transaction/Swap/index.tsx
> [Issue-1760] The update version popup is still displayed if the user has not updated

- src/constants/index.ts
- src/providers/WebRunnerProvider/WebRunner.tsx
> [Issue-1761] Check and update android WebView min version

- src/AppNavigator.tsx
- src/components/Modal/PasswordModal.tsx
- src/hooks/screen/Home/Crypto/useReceiveQR.ts
- src/providers/DataContext.tsx
- src/screens/Account/AccountsScreen/index.tsx
- src/screens/Account/ExportAllAccount/index.tsx
- src/screens/Home/Crypto/TokenGroups.tsx
- src/screens/Home/Crypto/TokenSearchModal.tsx
- src/screens/Home/index.tsx
- src/stores/index.ts
> [Issue-1775] Review app performance (v1.1.78)

- src/App.tsx
> [Issue-1491] Fix bug timeout when re-open the app

- src/components/Modal/NoticeModal/index.tsx
- src/components/design-system-ui/page-icon/index.tsx
- src/constants/index.ts
- src/screens/Home/index.tsx
- src/screens/WebViewDebugger.tsx
> [Issue-1801] Add warning not support IOS <16.4

- .github/workflows/build-internal.yml
> [Issue-1753] Update github workflow

- src/providers/WebRunnerProvider/WebRunner.tsx
> [Issue-1821] Fix bug can't open app on HarmornyOS

- src/screens/NetworkSettingDetail.tsx
> [Issue-1868] Unified account - Update UI Network details screen for TON

- .github/workflows/build-internal.yml
- src/screens/Settings/Security/DAppAccess/DAppAccessDetailScreen.tsx
- src/screens/Settings/Security/DAppAccess/index.tsx
> [Issue-1857] Unified account - Bug related to Connect & Manage dApp

- .github/workflows/build-internal.yml
- ios/SubWalletMobile.xcodeproj/project.pbxproj
> [Issue-1909] Fix auto build

- src/hooks/screen/Home/Crypto/useBuyToken.ts
> [Issue-1853] Wrong navigation link of Coinbase when Buy token (on Android)

- ios/Podfile.lock
- src/App.tsx
- src/constants/index.ts
- src/hooks/static-content/useGetShowReviewPopupScreen.ts
- src/screens/Transaction/CancelUnstake/index.tsx
- src/screens/Transaction/ClaimBridge/index.tsx
- src/screens/Transaction/ClaimReward/index.tsx
- src/screens/Transaction/Earn/index.tsx
- src/screens/Transaction/NFT/index.tsx
- src/screens/Transaction/SendFund/index.tsx
- src/screens/Transaction/Swap/index.tsx
- src/screens/Transaction/TransactionDone/index.tsx
> [Issue-1882] Add popup review app after swap successfully

- package.json
- src/components/Modal/common/TokenSelector.tsx
- src/screens/Home/Crypto/TokenSearchModal.tsx
> [Issue-1895] Improve UI related to Select token screen

- src/screens/Confirmations/variants/Transaction/variants/Swap.tsx
- src/screens/Transaction/Swap/index.tsx
- src/utils/sort/token.ts
> [Issue-1920] fix bug when perform swap on SimpleSwap

- ios/Podfile.lock
- src/components/Modal/Earning/EarningPoolDetailModal/index.tsx
- src/components/Tag/EarningTypeTag/index.tsx
- src/hooks/earning/useGetEarningPoolDetailModalData.ts
- src/utils/earning.ts
> [Issue-1931] Fix error bug when select TAO earning option

- src/screens/Home/Browser/BrowserTab.tsx
> [Issue-1958] fix bug show Share screen on some dApp on android

- src/screens/Settings/index.tsx
> [Issue-1956] Update link for "Contact support" action
